name: Deploy to Firebase project production

on:
  push:
    branches: [main] # ステージング用は「[develop]」
env:
  FIREBASE_TOKEN: ${{ secrets.PW }}
  FIREBASE_PROJECT_ID_PROD: ${{ secrets.PW }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: macos-latest 
    # ↑ ubuntu や windows なども指定可能
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        # ↑ 「@master」とかもあってブランチ名っぽいですが、ブランチ名ではなく
        # GitHub Actions が提供している `チェックアウトアクション` のバージョン名なので注意
      - name: Create .env file
        run: echo "test ${{ secrets.PW }}" > .env
      - name: open env
        run: cat .env
